name: brainframe-client
summary: A smart vision platform that is built to be easy to scale and deploy
description: >
  BrainFrame is a smart vision platform that is built to be easy to scale,
  highly configurable, and deployable on-premises or to the cloud. This is its
  client.

  Powered by our automatic algorithm fusion and optimization engine,
  BrainFrame enables plug and play integration of VisionCapsules. This platform
  turns any connected camera into a smart sensor for sophisticated monitoring
  and inspection tasks, serving a variety of vertical markets.

  The client makes it easy to configure video streams, set up zones, and manage
  VisionCapsules without any programming experience.
# TODO: Update to core20 when the kde-neon extension supports it.
#       See: https://bugs.kde.org/show_bug.cgi?id=427576
base: core18
confinement: strict
grade: stable
adopt-info: brainframe-client

parts:
  brainframe-client:
    plugin: nil
    override-pull: |
      snapcraftctl pull
      VERSION=$(awk -F'[ ="]+' '$1 == "version" { print $2 }' pyproject.toml)
      snapcraftctl set-version ${VERSION}
    override-build: |

      # Install dependencies
      pip3 install --upgrade pip wheel

      # These packages are installed by apt, and Poetry will try to uninstall
      # them because their versions don't match ours. It will then fail since
      # they're dist-packages. As a workaround, we install them with pip so
      # that Poetry removes those instead.
      pip3 install --ignore-installed httplib2 pyyaml

      export PYTHON_INSTALL_DIR=$SNAPCRAFT_PART_INSTALL/usr/local/lib/python3.6/site-packages
      mkdir -p $PYTHON_INSTALL_DIR

      # Install PyQt5 commercial and SIP
      PYQT_VERSION=5.12.2
      mkdir pyqt && cd pyqt
      sudo update-ca-certificates && \
          wget --quiet https://brainframe-build-resources.s3-us-west-1.amazonaws.com/PyQt5_commercial-$PYQT_VERSION.tar.gz && \
          wget --quiet https://brainframe-build-resources.s3-us-west-1.amazonaws.com/pyqt-commercial.sip
      tar --strip-components=1 -xzf PyQt5_commercial-$PYQT_VERSION.tar.gz
      cp pyqt-commercial.sip sip/.
      python3 configure.py \
          --confirm-license \
          --destdir=$PYTHON_INSTALL_DIR \
          --bindir=/usr/local/bin
      CPATH=/usr/local/include/python3.6 make install

      # Install Poetry
      curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py \
        | python3 - --version 1.1.4
      export PATH=$HOME/.poetry/bin:$PATH

      # Install all Poetry dependencies globally
      poetry config virtualenvs.create false
      poetry install --no-root --no-dev

      # Copy the project
      cp -r brainframe_qt/ $PYTHON_INSTALL_DIR/
      # Remove all undesirable file types
      for undesirable in "*.pyc" "__pycache__"
        do find $PYTHON_INSTALL_DIR/brainframe_qt/ -name "$undesirable" -delete
      done

      # Add the main Python file
      cp brainframe_client.py $PYTHON_INSTALL_DIR/
    source: .
    build-packages:
      # Basic Python packages
      - python3-pip
      - python3-dev
      - python3-setuptools
      - python3-distutils
      # Poetry dependencies
      - python3-venv
      - git
      # PyGObject dependencies
      - pkg-config
      - libcairo2-dev
      - libgirepository1.0-dev
      # Qt dependencies
      - qt5-default
      - pyqt5-dev-tools
      - qttools5-dev-tools
    stage-packages:
      # Basic Python packages
      - python3-setuptools
      - python3-distutils
      # For theming
      - adwaita-qt
      # PyQt
      - python3-pyqt5
      - python3-pyqt5.qtsvg
      # PyGObject dependencies
      - libgirepository-1.0-1
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-libav
      - gir1.2-gst-plugins-base-1.0
    build-environment:
      # https://bugs.launchpad.net/snapcraft/+bug/1802345
      - C_INCLUDE_PATH: /usr/include/python3.6m

apps:
  brainframe-client:
    command: python3 $SNAP/usr/local/lib/python3.6/site-packages/brainframe_client.py
    extensions:
      - kde-neon
    plugs:
      - opengl
      - network
      - home
    environment:
      PYTHONPATH: "$SNAP/usr/src/brainframe-api:$SNAP/usr/local/lib/python3.6/site-packages:$PYTHONPATH"
      QT_STYLE_OVERRIDE: "adwaita-dark"
