from .alerts import AlertStubMixin
from .analysis import AnalysisStubMixin
from .engine_configurations import EngineConfigurationStubMixin
from .identities import IdentityStubMixin
from .plugins import PluginStubMixin
from .streams import StreamStubMixin
from .zone_statuses import ZoneStatusStubMixin
from .zones import ZoneStubMixin
from .storage import StorageStubMixin
from .alarms import ZoneAlarmStubMixin
from .process_image import ProcessImageStubMixIn
