from .alarm_creation.alarm_creation import AlarmCreationDialog
from .task_configuration.task_configuration import TaskConfiguration
from .license_agreement.license_agreement import LicenseAgreement
from .stream_configuration.stream_configuration import StreamConfigurationDialog
