from .about_page.about_page import AboutPage
from .alarm_creation.alarm_creation import AlarmCreationDialog
from .identity_configuration.identity_configuration import IdentityConfiguration
from .license_agreement.license_agreement import LicenseAgreement
from .stream_configuration.stream_configuration import StreamConfigurationDialog
from .task_configuration.task_configuration import TaskConfiguration
