from .about_page.about_page import AboutPage
from .alarm_creation.alarm_creation import AlarmCreationDialog
from .alert_entry_popup.alert_entry_popup import AlertEntryPopup
# from .identity_configuration.identity_configuration import IdentityConfiguration
from .identity_configuration_2.identity_configuration import IdentityConfiguration
from .license_agreement.license_agreement import LicenseAgreement
from .standard_error.standard_error import StandardError
from .stream_configuration.stream_configuration import StreamConfigurationDialog
from .task_configuration.task_configuration import TaskConfiguration
from .plugin_configuration.plugin_config import PluginConfigDialog
from .video_configuration import RenderConfiguration
